project_id = "dyelzdhxctljbobyoqxr"

[functions.process-subscription-payment]
verify_jwt = false

[functions.payment-callback]
verify_jwt = false

[functions.process-promotion-payment]
verify_jwt = false

[functions.promotion-callback]
verify_jwt = false
